version: '3'
volumes: 
  jenkins_home:
  gitlab_data:
  gitlab_log:
  gitlab_config:
  ldap_data:
  artifacts_data:
services:
  openldap:
    build: 
      context: ./ldap
      dockerfile: Dockerfile
    image: trumhemcut/openldap:latest
    restart: always
    container_name: nt-openldap
    tty: true
    stdin_open: true
    ports:
      - "389:389"
      - "636:636"
    volumes: 
      - 'ldap_data:/data'
    hostname: "ldap.yourcompany.com"
  ldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: nt-ldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "nt-openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8082:80"
    depends_on:
     - openldap
  gitlab:
    container_name: nt-gitlab
    build:
      context: ./gitlab
      dockerfile: Dockerfile
    image: 'trumhemcut/gitlab'
    restart: always
    hostname: 'git.yourcompany.com'
    ports: 
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes: 
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_log:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
      - ./gitlab/gitlab.rb:/etc/gitlab/gitlab.rb
    depends_on: 
      - openldap
    extra_hosts: 
      - "jenkins.yourcompany.com:${HOST_IP}"
  jenkins:
    container_name: nt-jenkins
    build: 
      context: ./jenkins
    image: trumhemcut/jenkins:latest
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - 'jenkins_home:/var/jenkins_home'
      - 'artifacts_data:/artifacts'
    hostname: 'jenkins.yourcompany.com'
    ports: 
      - '8080:8080'
      - '50000:50000'
    extra_hosts: 
      - "git.yourcompany.com:${HOST_IP}"
    depends_on: 
      - gitlab
  sonarqube:
    container_name: nt-sonarqube
    image: sonarqube
    ports: 
      - '9000:9000'
      - '9092:9092'